//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSServiceClient.DGSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DGSService.IDGSWCFService")]
    public interface IDGSWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetInfoService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetInfoServiceResponse")]
        string agentGetInfoService(string agent, string idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetInfoService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetInfoServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetInfoServiceAsync(string agent, string idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentFindListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentFindListServiceResponse")]
        string agentFindListService(string agent, string name, string idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentFindListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentFindListServiceResponse")]
        System.Threading.Tasks.Task<string> agentFindListServiceAsync(string agent, string name, string idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetAgentsListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetAgentsListServiceResponse")]
        string agentGetAgentsListService(string idAgent, string decimasl, string trunc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetAgentsListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetAgentsListServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetAgentsListServiceAsync(string idAgent, string decimasl, string trunc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetDistributorService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetDistributorServiceResponse")]
        string agentGetDistributorService(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetDistributorService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetDistributorServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetDistributorServiceAsync(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetInfoDistributorService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetInfoDistributorServiceResponse")]
        string agentGetInfoDistributorService(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetInfoDistributorService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetInfoDistributorServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetInfoDistributorServiceAsync(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetListServiceResponse")]
        string agentGetListService(string pridUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetListServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetListServiceAsync(string pridUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetListByBookService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetListByBookServiceResponse")]
        string agentGetListByBookService(string idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetListByBookService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetListByBookServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetListByBookServiceAsync(string idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetNotesService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetNotesServiceResponse")]
        string agentGetNotesService(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetNotesService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetNotesServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetNotesServiceAsync(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetPlayersListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetPlayersListServiceResponse")]
        string agentGetPlayersListService(string Idagent, string decimals, string trunc, string idCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetPlayersListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetPlayersListServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetPlayersListServiceAsync(string Idagent, string decimals, string trunc, string idCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetPlayersIDService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetPlayersIDServiceResponse")]
        string agentGetPlayersIDService(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetPlayersIDService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetPlayersIDServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetPlayersIDServiceAsync(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetStatisticsService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetStatisticsServiceResponse")]
        string agentGetStatisticsService(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetStatisticsService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetStatisticsServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetStatisticsServiceAsync(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentLineTypesGetListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentLineTypesGetListServiceResponse")]
        string agentLineTypesGetListService(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentLineTypesGetListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentLineTypesGetListServiceResponse")]
        System.Threading.Tasks.Task<string> agentLineTypesGetListServiceAsync(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentLineTypesGetListAddedService", ReplyAction="http://tempuri.org/IDGSWCFService/agentLineTypesGetListAddedServiceResponse")]
        string agentLineTypesGetListAddedService(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentLineTypesGetListAddedService", ReplyAction="http://tempuri.org/IDGSWCFService/agentLineTypesGetListAddedServiceResponse")]
        System.Threading.Tasks.Task<string> agentLineTypesGetListAddedServiceAsync(string idAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentRightsGetListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentRightsGetListServiceResponse")]
        string agentRightsGetListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentRightsGetListService", ReplyAction="http://tempuri.org/IDGSWCFService/agentRightsGetListServiceResponse")]
        System.Threading.Tasks.Task<string> agentRightsGetListServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/addAgentService", ReplyAction="http://tempuri.org/IDGSWCFService/addAgentServiceResponse")]
        string addAgentService(DGSRestServices.Model.Class.AgentModel agentModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/addAgentService", ReplyAction="http://tempuri.org/IDGSWCFService/addAgentServiceResponse")]
        System.Threading.Tasks.Task<string> addAgentServiceAsync(DGSRestServices.Model.Class.AgentModel agentModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/updateAgentService", ReplyAction="http://tempuri.org/IDGSWCFService/updateAgentServiceResponse")]
        string updateAgentService(DGSRestServices.Model.Class.AgentModel agentModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/updateAgentService", ReplyAction="http://tempuri.org/IDGSWCFService/updateAgentServiceResponse")]
        System.Threading.Tasks.Task<string> updateAgentServiceAsync(DGSRestServices.Model.Class.AgentModel agentModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/deleteAgentService", ReplyAction="http://tempuri.org/IDGSWCFService/deleteAgentServiceResponse")]
        string deleteAgentService(string idAgent, string idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/deleteAgentService", ReplyAction="http://tempuri.org/IDGSWCFService/deleteAgentServiceResponse")]
        System.Threading.Tasks.Task<string> deleteAgentServiceAsync(string idAgent, string idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/addBookService", ReplyAction="http://tempuri.org/IDGSWCFService/addBookServiceResponse")]
        string addBookService(DGSRestServices.Model.Class.BookModel bookModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/addBookService", ReplyAction="http://tempuri.org/IDGSWCFService/addBookServiceResponse")]
        System.Threading.Tasks.Task<string> addBookServiceAsync(DGSRestServices.Model.Class.BookModel bookModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/usersGetIDService", ReplyAction="http://tempuri.org/IDGSWCFService/usersGetIDServiceResponse")]
        string usersGetIDService(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/usersGetIDService", ReplyAction="http://tempuri.org/IDGSWCFService/usersGetIDServiceResponse")]
        System.Threading.Tasks.Task<string> usersGetIDServiceAsync(string loginName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDGSWCFServiceChannel : DGSServiceClient.DGSService.IDGSWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DGSWCFServiceClient : System.ServiceModel.ClientBase<DGSServiceClient.DGSService.IDGSWCFService>, DGSServiceClient.DGSService.IDGSWCFService {
        
        public DGSWCFServiceClient() {
        }
        
        public DGSWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DGSWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DGSWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DGSWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string agentGetInfoService(string agent, string idUser) {
            return base.Channel.agentGetInfoService(agent, idUser);
        }
        
        public System.Threading.Tasks.Task<string> agentGetInfoServiceAsync(string agent, string idUser) {
            return base.Channel.agentGetInfoServiceAsync(agent, idUser);
        }
        
        public string agentFindListService(string agent, string name, string idUser) {
            return base.Channel.agentFindListService(agent, name, idUser);
        }
        
        public System.Threading.Tasks.Task<string> agentFindListServiceAsync(string agent, string name, string idUser) {
            return base.Channel.agentFindListServiceAsync(agent, name, idUser);
        }
        
        public string agentGetAgentsListService(string idAgent, string decimasl, string trunc) {
            return base.Channel.agentGetAgentsListService(idAgent, decimasl, trunc);
        }
        
        public System.Threading.Tasks.Task<string> agentGetAgentsListServiceAsync(string idAgent, string decimasl, string trunc) {
            return base.Channel.agentGetAgentsListServiceAsync(idAgent, decimasl, trunc);
        }
        
        public string agentGetDistributorService(string idAgent) {
            return base.Channel.agentGetDistributorService(idAgent);
        }
        
        public System.Threading.Tasks.Task<string> agentGetDistributorServiceAsync(string idAgent) {
            return base.Channel.agentGetDistributorServiceAsync(idAgent);
        }
        
        public string agentGetInfoDistributorService(string idAgent) {
            return base.Channel.agentGetInfoDistributorService(idAgent);
        }
        
        public System.Threading.Tasks.Task<string> agentGetInfoDistributorServiceAsync(string idAgent) {
            return base.Channel.agentGetInfoDistributorServiceAsync(idAgent);
        }
        
        public string agentGetListService(string pridUser) {
            return base.Channel.agentGetListService(pridUser);
        }
        
        public System.Threading.Tasks.Task<string> agentGetListServiceAsync(string pridUser) {
            return base.Channel.agentGetListServiceAsync(pridUser);
        }
        
        public string agentGetListByBookService(string idBook) {
            return base.Channel.agentGetListByBookService(idBook);
        }
        
        public System.Threading.Tasks.Task<string> agentGetListByBookServiceAsync(string idBook) {
            return base.Channel.agentGetListByBookServiceAsync(idBook);
        }
        
        public string agentGetNotesService(string idAgent) {
            return base.Channel.agentGetNotesService(idAgent);
        }
        
        public System.Threading.Tasks.Task<string> agentGetNotesServiceAsync(string idAgent) {
            return base.Channel.agentGetNotesServiceAsync(idAgent);
        }
        
        public string agentGetPlayersListService(string Idagent, string decimals, string trunc, string idCurrency) {
            return base.Channel.agentGetPlayersListService(Idagent, decimals, trunc, idCurrency);
        }
        
        public System.Threading.Tasks.Task<string> agentGetPlayersListServiceAsync(string Idagent, string decimals, string trunc, string idCurrency) {
            return base.Channel.agentGetPlayersListServiceAsync(Idagent, decimals, trunc, idCurrency);
        }
        
        public string agentGetPlayersIDService(string idAgent) {
            return base.Channel.agentGetPlayersIDService(idAgent);
        }
        
        public System.Threading.Tasks.Task<string> agentGetPlayersIDServiceAsync(string idAgent) {
            return base.Channel.agentGetPlayersIDServiceAsync(idAgent);
        }
        
        public string agentGetStatisticsService(string idAgent) {
            return base.Channel.agentGetStatisticsService(idAgent);
        }
        
        public System.Threading.Tasks.Task<string> agentGetStatisticsServiceAsync(string idAgent) {
            return base.Channel.agentGetStatisticsServiceAsync(idAgent);
        }
        
        public string agentLineTypesGetListService(string idAgent) {
            return base.Channel.agentLineTypesGetListService(idAgent);
        }
        
        public System.Threading.Tasks.Task<string> agentLineTypesGetListServiceAsync(string idAgent) {
            return base.Channel.agentLineTypesGetListServiceAsync(idAgent);
        }
        
        public string agentLineTypesGetListAddedService(string idAgent) {
            return base.Channel.agentLineTypesGetListAddedService(idAgent);
        }
        
        public System.Threading.Tasks.Task<string> agentLineTypesGetListAddedServiceAsync(string idAgent) {
            return base.Channel.agentLineTypesGetListAddedServiceAsync(idAgent);
        }
        
        public string agentRightsGetListService() {
            return base.Channel.agentRightsGetListService();
        }
        
        public System.Threading.Tasks.Task<string> agentRightsGetListServiceAsync() {
            return base.Channel.agentRightsGetListServiceAsync();
        }
        
        public string addAgentService(DGSRestServices.Model.Class.AgentModel agentModel) {
            return base.Channel.addAgentService(agentModel);
        }
        
        public System.Threading.Tasks.Task<string> addAgentServiceAsync(DGSRestServices.Model.Class.AgentModel agentModel) {
            return base.Channel.addAgentServiceAsync(agentModel);
        }
        
        public string updateAgentService(DGSRestServices.Model.Class.AgentModel agentModel) {
            return base.Channel.updateAgentService(agentModel);
        }
        
        public System.Threading.Tasks.Task<string> updateAgentServiceAsync(DGSRestServices.Model.Class.AgentModel agentModel) {
            return base.Channel.updateAgentServiceAsync(agentModel);
        }
        
        public string deleteAgentService(string idAgent, string idUser) {
            return base.Channel.deleteAgentService(idAgent, idUser);
        }
        
        public System.Threading.Tasks.Task<string> deleteAgentServiceAsync(string idAgent, string idUser) {
            return base.Channel.deleteAgentServiceAsync(idAgent, idUser);
        }
        
        public string addBookService(DGSRestServices.Model.Class.BookModel bookModel) {
            return base.Channel.addBookService(bookModel);
        }
        
        public System.Threading.Tasks.Task<string> addBookServiceAsync(DGSRestServices.Model.Class.BookModel bookModel) {
            return base.Channel.addBookServiceAsync(bookModel);
        }
        
        public string usersGetIDService(string loginName) {
            return base.Channel.usersGetIDService(loginName);
        }
        
        public System.Threading.Tasks.Task<string> usersGetIDServiceAsync(string loginName) {
            return base.Channel.usersGetIDServiceAsync(loginName);
        }
    }
}
