//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT()
        {
            this.AGENT11 = new HashSet<AGENT>();
            this.AGENTACCOUNTING = new HashSet<AGENTACCOUNTING>();
            this.AGENTLINETYPE = new HashSet<AGENTLINETYPE>();
            this.AGENTLOGONS = new HashSet<AGENTLOGONS>();
            this.AGENTTRANSACTION = new HashSet<AGENTTRANSACTION>();
            this.AGENTWEEKLYBALANCE = new HashSet<AGENTWEEKLYBALANCE>();
        }
    
        public int IdAgent { get; set; }
        public short IdCurrency { get; set; }
        public short IdBook { get; set; }
        public string Agent1 { get; set; }
        public byte IdAgentType { get; set; }
        public Nullable<short> IdGrouping { get; set; }
        public Nullable<int> Distributor { get; set; }
        public string Password { get; set; }
        public bool Enable { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public bool IsDistributor { get; set; }
        public bool DontXferPlayerActivity { get; set; }
        public Nullable<bool> IsDistributed { get; set; }
        public byte CommSports { get; set; }
        public byte CommCasino { get; set; }
        public byte CommHorses { get; set; }
        public decimal PerHeadSports { get; set; }
        public decimal PerHeadCasino { get; set; }
        public decimal PerHeadHorses { get; set; }
        public bool OnlineAccess { get; set; }
        public string OnlineMessage { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
        public Nullable<short> IdLineType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENT> AGENT11 { get; set; }
        public virtual AGENT AGENT2 { get; set; }
        public virtual AGENTTYPE AGENTTYPE { get; set; }
        public virtual BOOK BOOK { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual GROUPING GROUPING { get; set; }
        public virtual LINETYPE LINETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTACCOUNTING> AGENTACCOUNTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTLINETYPE> AGENTLINETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTLOGONS> AGENTLOGONS { get; set; }
        public virtual AGENTNOTES AGENTNOTES { get; set; }
        public virtual AGENTSTATISTIC AGENTSTATISTIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTTRANSACTION> AGENTTRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTWEEKLYBALANCE> AGENTWEEKLYBALANCE { get; set; }
    }
}
