//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTLINETYPE
    {
        public int Idagent { get; set; }
        public short IdLineType { get; set; }
        public System.DateTime Lastmodification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual LINETYPE LINETYPE { get; set; }
    }
}
