//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTWEEKLYBALANCE
    {
        public int IdAgent { get; set; }
        public System.DateTime Week { get; set; }
        public decimal Balance { get; set; }
        public decimal MakeUp { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual AGENT AGENT { get; set; }
    }
}
