//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTCOMMISSION
    {
        public int IdAgent { get; set; }
        public byte CommSports { get; set; }
        public byte CommCasino { get; set; }
        public byte CommHorses { get; set; }
        public decimal CommPerHead { get; set; }
    }
}
