//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTLOGONS
    {
        public int IdAgentLogons { get; set; }
        public int IdAgent { get; set; }
        public System.DateTime PlacedDate { get; set; }
        public string IP { get; set; }
    
        public virtual AGENT AGENT { get; set; }
    }
}
