//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AggLimitWork
    {
        public int Key { get; set; }
        public int AccountID { get; set; }
        public int RaceID { get; set; }
        public byte TicketType { get; set; }
        public string Selections { get; set; }
        public decimal Amount { get; set; }
        public int TicketID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual RaceTicketMain RaceTicketMain { get; set; }
    }
}
