//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRISKLOG
    {
        public int IdAtRiskLog { get; set; }
        public int IdPlayer { get; set; }
        public double OldCurrentBalance { get; set; }
        public double NewCurrentBalance { get; set; }
        public double OldAmountAtRisk { get; set; }
        public double NewAmountAtRisk { get; set; }
        public double OldAvailBalance { get; set; }
        public double NewAvailBalance { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
