//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRISKLOG
    {
        public int IdAtRiskLog { get; set; }
        public int IdPlayer { get; set; }
        public double OldCurrentBalance { get; set; }
        public double NewCurrentBalance { get; set; }
        public double OldAmountAtRisk { get; set; }
        public double NewAmountAtRisk { get; set; }
        public double OldAvailBalance { get; set; }
        public double NewAvailBalance { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
