//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNERTYPELANG
    {
        public short IdBannerType { get; set; }
        public byte IdLanguage { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual BANNERTYPE BANNERTYPE { get; set; }
        public virtual Language Language { get; set; }
    }
}
