//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNERTYPELANG
    {
        public short IdBannerType { get; set; }
        public byte IdLanguage { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual BANNERTYPE BANNERTYPE { get; set; }
        public virtual Language Language { get; set; }
    }
}
