//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKCLIENTPREFERENCES
    {
        public short IdBook { get; set; }
        public bool AllCanadianLine { get; set; }
        public bool BuyPointsInPeriods { get; set; }
        public bool DisplayBothTeamsOnTotals { get; set; }
        public bool MLBHalvesUseLP { get; set; }
        public bool UseTrueOdds { get; set; }
        public bool RoundType { get; set; }
        public string MaxWagerCheck { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
