//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKPREFIX
    {
        public short IdBook { get; set; }
        public string PreName { get; set; }
        public int Consecutive { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
