//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKCLIENTPREFERENCES
    {
        public short IdBook { get; set; }
        public bool AllCanadianLine { get; set; }
        public bool BuyPointsInPeriods { get; set; }
        public bool DisplayBothTeamsOnTotals { get; set; }
        public bool MLBHalvesUseLP { get; set; }
        public bool UseTrueOdds { get; set; }
        public bool RoundType { get; set; }
        public string MaxWagerCheck { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
