//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDDEFODDS
    {
        public int IdCardDef { get; set; }
        public byte TeamsNumber { get; set; }
        public byte NumWins { get; set; }
        public byte NumLosses { get; set; }
        public byte NumTies { get; set; }
        public int Odds { get; set; }
        public bool Enable { get; set; }
        public string CaseTie { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual CARDDEF CARDDEF { get; set; }
    }
}
