//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDLINES
    {
        public int IDCardHeader { get; set; }
        public int IdGame { get; set; }
        public byte Play { get; set; }
        public short GameNumber { get; set; }
        public Nullable<double> Points { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        public virtual CARDHEADER CARDHEADER { get; set; }
    }
}
