//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDDEFSPORTS
    {
        public int IdCardDef { get; set; }
        public string IdSport { get; set; }
        public double SpreadPoints { get; set; }
        public double TotalPoints { get; set; }
        public bool Enable { get; set; }
        public System.DateTime LastModification { get; set; }
        public short lastModificationUser { get; set; }
    
        public virtual CARDDEF CARDDEF { get; set; }
    }
}
