//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDDEFSPORTS
    {
        public int IdCardDef { get; set; }
        public string IdSport { get; set; }
        public double SpreadPoints { get; set; }
        public double TotalPoints { get; set; }
        public bool Enable { get; set; }
        public System.DateTime LastModification { get; set; }
        public short lastModificationUser { get; set; }
    
        public virtual CARDDEF CARDDEF { get; set; }
    }
}
