//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASINOTRANSACTIONS
    {
        public int TransactionId { get; set; }
        public Nullable<int> IdPlayerAccounting { get; set; }
        public string Login { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CasinoGameId { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string Mode { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
    }
}
