//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTCHANGEDLINES
    {
        public int IdLineType { get; set; }
        public int IdGame { get; set; }
        public int TeamNumber { get; set; }
        public System.DateTime VisitorSpreadDate { get; set; }
        public System.DateTime HomeSpreadDate { get; set; }
        public System.DateTime TotalOverDate { get; set; }
        public System.DateTime TotalUnderDate { get; set; }
        public System.DateTime VisitorMoneyLineDate { get; set; }
        public System.DateTime HomeMoneyLineDate { get; set; }
        public System.DateTime VisitorSpecialDate { get; set; }
        public System.DateTime HomeSpecialDate { get; set; }
    }
}
