//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTCHANGEDLINES
    {
        public int IdLineType { get; set; }
        public int IdGame { get; set; }
        public int TeamNumber { get; set; }
        public System.DateTime VisitorSpreadDate { get; set; }
        public System.DateTime HomeSpreadDate { get; set; }
        public System.DateTime TotalOverDate { get; set; }
        public System.DateTime TotalUnderDate { get; set; }
        public System.DateTime VisitorMoneyLineDate { get; set; }
        public System.DateTime HomeMoneyLineDate { get; set; }
        public System.DateTime VisitorSpecialDate { get; set; }
        public System.DateTime HomeSpecialDate { get; set; }
    }
}
