//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CW_AGENT
    {
        public int IDAgent { get; set; }
        public string Agent { get; set; }
        public bool isDistributor { get; set; }
        public Nullable<int> idDistributor { get; set; }
        public string Distributor { get; set; }
        public byte IdAgentType { get; set; }
        public string AgentType { get; set; }
        public bool DontXfer { get; set; }
        public bool IsDistributed { get; set; }
        public double MakeUp { get; set; }
        public double NewMakeUp { get; set; }
        public double PBalance { get; set; }
        public double NBalance { get; set; }
        public Nullable<short> idGroup { get; set; }
        public byte IdCurrency { get; set; }
        public decimal CW_Total { get; set; }
        public decimal CW_Sports { get; set; }
        public decimal CW_Casino { get; set; }
        public decimal CW_Horses { get; set; }
        public decimal CW_CommSports { get; set; }
        public decimal CW_CommCasino { get; set; }
        public decimal CW_CommHorses { get; set; }
        public decimal CW_PHSports { get; set; }
        public decimal CW_PHCasino { get; set; }
        public decimal CW_PHHorses { get; set; }
        public decimal CW_DistTotal { get; set; }
        public decimal CW_DistSports { get; set; }
        public decimal CW_DistCasino { get; set; }
        public decimal CW_DistHorses { get; set; }
        public int CW_PlayersTotal { get; set; }
        public int CW_PlayersSports { get; set; }
        public int CW_PlayersCasino { get; set; }
        public int CW_PlayersHorses { get; set; }
        public decimal CW_GrossTotal { get; set; }
        public decimal CW_GrossSports { get; set; }
        public decimal CW_GrossCasino { get; set; }
        public decimal CW_GrossHorses { get; set; }
        public decimal CW_AgentCPSports { get; set; }
        public decimal CW_AgentCPCasino { get; set; }
        public decimal CW_AgentCPHorses { get; set; }
        public decimal CW_AgentPHSports { get; set; }
        public decimal CW_AgentPHCasino { get; set; }
        public decimal CW_AgentPHHorses { get; set; }
    }
}
