//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryOdds
    {
        public int RaceID { get; set; }
        public byte EntryNum { get; set; }
        public Nullable<byte> MTP { get; set; }
        public string MLFrac { get; set; }
        public string WinOdds { get; set; }
        public Nullable<decimal> WinProb { get; set; }
        public Nullable<decimal> WinTotal { get; set; }
        public Nullable<decimal> PlaceTotal { get; set; }
        public Nullable<decimal> ShowTotal { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
