//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EposVoid
    {
        public int WagerID { get; set; }
        public string TicketType { get; set; }
        public int TicketNumber { get; set; }
        public System.DateTime VoidDateTime { get; set; }
        public short IdUser { get; set; }
        public int ManagerID { get; set; }
        public System.DateTime OpDate { get; set; }
    }
}
