//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EposSportsbookTransfer
    {
        public int TransferID { get; set; }
        public int EposPlayerID { get; set; }
        public int IdPlayer { get; set; }
        public System.DateTime TransferDateTime { get; set; }
        public string CurrCode { get; set; }
        public decimal CurrAmount { get; set; }
        public decimal ExchangeRate { get; set; }
        public int LocationID { get; set; }
        public int TerminalID { get; set; }
        public short IdUser { get; set; }
        public System.DateTime OpDate { get; set; }
    }
}
