//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EposPlayer
    {
        public int EposPlayerID { get; set; }
        public string AcctNum { get; set; }
        public Nullable<int> IdPlayer { get; set; }
        public string PIN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string Phone1Desc { get; set; }
        public string Phone1 { get; set; }
        public string Phone2Desc { get; set; }
        public string Phone2 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateManagerID { get; set; }
        public int CreateLocationID { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
