//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EposSportsbookTransfer
    {
        public int TransferID { get; set; }
        public int EposPlayerID { get; set; }
        public int IdPlayer { get; set; }
        public System.DateTime TransferDateTime { get; set; }
        public string CurrCode { get; set; }
        public decimal CurrAmount { get; set; }
        public decimal ExchangeRate { get; set; }
        public int LocationID { get; set; }
        public int TerminalID { get; set; }
        public short IdUser { get; set; }
        public System.DateTime OpDate { get; set; }
    }
}
