//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EposCurrency
    {
        public string CurrCode { get; set; }
        public string CurrName { get; set; }
        public short RoundTo { get; set; }
        public string FormatStr { get; set; }
    }
}
