//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EposVoid
    {
        public int WagerID { get; set; }
        public string TicketType { get; set; }
        public int TicketNumber { get; set; }
        public System.DateTime VoidDateTime { get; set; }
        public short IdUser { get; set; }
        public int ManagerID { get; set; }
        public System.DateTime OpDate { get; set; }
    }
}
