//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETSRequestLog
    {
        public int ReqID { get; set; }
        public string ETSServerName { get; set; }
        public string PathInfo { get; set; }
        public string ClientIP { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> TermSessID { get; set; }
        public Nullable<int> RequestBytes { get; set; }
        public Nullable<int> ResponseBytes { get; set; }
    }
}
