//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETSRequestLog
    {
        public int ReqID { get; set; }
        public string ETSServerName { get; set; }
        public string PathInfo { get; set; }
        public string ClientIP { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> TermSessID { get; set; }
        public Nullable<int> RequestBytes { get; set; }
        public Nullable<int> ResponseBytes { get; set; }
    }
}
