//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FREEPLAYOFFICEOPTIONS
    {
        public byte IdOffice { get; set; }
        public string IdSport { get; set; }
        public byte Line { get; set; }
        public byte WagerType { get; set; }
        public bool Online { get; set; }
        public bool Onlocal { get; set; }
    }
}
