//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMERELATEDOPTIONS
    {
        public short IdProfile { get; set; }
        public string IdSport { get; set; }
        public byte IdPeriod { get; set; }
        public bool MLFav_Over { get; set; }
        public bool MLFav_Under { get; set; }
        public bool MLDog_Over { get; set; }
        public bool MLDog_Under { get; set; }
        public bool SprFav_Over { get; set; }
        public bool SprFav_Under { get; set; }
        public bool SprDog_Over { get; set; }
        public bool SprDog_Under { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
