//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMESTATPUBQUEUE
    {
        public int IdGameStatPubQueue { get; set; }
        public int IdGame { get; set; }
        public string IdSport { get; set; }
        public System.DateTime GameDateTime { get; set; }
        public int VisitorNumber { get; set; }
        public string GameStat { get; set; }
        public bool HookUps { get; set; }
        public bool Online { get; set; }
        public bool OnLocal { get; set; }
        public bool ShortGame { get; set; }
        public System.DateTime EventDate { get; set; }
        public bool DateChanged { get; set; }
        public bool TimeChanged { get; set; }
        public Nullable<int> VisitorScore { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public string VisitorPitcher { get; set; }
        public string HomePitcher { get; set; }
        public byte PitcherChanged { get; set; }
        public byte SportType { get; set; }
        public short IdUser { get; set; }
        public short IdEvent { get; set; }
    }
}
