//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        public int IdGame { get; set; }
        public string VisitorTeam { get; set; }
        public string HomeTeam { get; set; }
        public string IdSport { get; set; }
        public short IdLeague { get; set; }
        public int IdGameType { get; set; }
        public short IdEvent { get; set; }
        public System.DateTime GameDateTime { get; set; }
        public byte NormalGame { get; set; }
        public int VisitorNumber { get; set; }
        public int HomeNumber { get; set; }
        public string GameStat { get; set; }
        public bool Graded { get; set; }
        public bool HookUps { get; set; }
        public bool Online { get; set; }
        public bool OnLocal { get; set; }
        public bool ShortGame { get; set; }
        public System.DateTime EventDate { get; set; }
        public bool DateChanged { get; set; }
        public bool TimeChanged { get; set; }
        public byte Period { get; set; }
        public int FamilyGame { get; set; }
        public int ParentGame { get; set; }
        public bool HasChildren { get; set; }
        public Nullable<int> VisitorScore { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public string VisitorPitcher { get; set; }
        public string HomePitcher { get; set; }
        public Nullable<System.DateTime> GradedDate { get; set; }
        public short NumTeams { get; set; }
        public byte PitcherChanged { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
        public Nullable<int> IdTeamVisitor { get; set; }
        public Nullable<int> IdTeamHome { get; set; }
        public Nullable<short> IdBannerType { get; set; }
    }
}
