//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMESYNCGAMES
    {
        public int IdGame { get; set; }
        public bool ToDelete { get; set; }
        public System.DateTime OldDate { get; set; }
        public byte ChangeType { get; set; }
    }
}
