//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMETNTPROPACTION
    {
        public int IdGame { get; set; }
        public short IdLineType { get; set; }
        public int TeamNumber { get; set; }
        public Nullable<int> Odds { get; set; }
        public Nullable<decimal> ActionRisk { get; set; }
        public Nullable<decimal> ActionWin { get; set; }
        public Nullable<float> ActionCount { get; set; }
        public Nullable<decimal> MasterActionRisk { get; set; }
        public Nullable<decimal> MasterActionWin { get; set; }
        public Nullable<float> MasterActionCount { get; set; }
        public Nullable<decimal> SumActionRisk { get; set; }
        public Nullable<decimal> SumActionWin { get; set; }
        public Nullable<float> SumActionCount { get; set; }
        public bool SendToLS { get; set; }
        public bool HideGame { get; set; }
        public bool SyncML { get; set; }
        public bool BoldML { get; set; }
    }
}
