//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMETYPE
    {
        public int IdGameType { get; set; }
        public string Short { get; set; }
        public string Description { get; set; }
        public bool AllowHookUps { get; set; }
        public bool AllowBuyPoints { get; set; }
        public int BkColor { get; set; }
        public int FkColor { get; set; }
    }
}
