//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMETYPE
    {
        public int IdGameType { get; set; }
        public string Short { get; set; }
        public string Description { get; set; }
        public bool AllowHookUps { get; set; }
        public bool AllowBuyPoints { get; set; }
        public int BkColor { get; set; }
        public int FkColor { get; set; }
    }
}
