//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMEIMPORTERSOURCES
    {
        public string ScheduleURL { get; set; }
        public byte ScheduleRefresh { get; set; }
        public string ScoresURL { get; set; }
        public byte ScoresRefresh { get; set; }
        public string LineChangesURL { get; set; }
        public byte LineChangesRefresh { get; set; }
        public bool ImportSchedule { get; set; }
        public bool ImportScores { get; set; }
        public bool ImportLineChanges { get; set; }
    }
}
