//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMEIMPORTEROPTIONS
    {
        public int IdSport { get; set; }
        public bool ProcessSchedule { get; set; }
        public bool ProcessLineChanges { get; set; }
        public int LineChangesBook { get; set; }
        public bool ProcessScores { get; set; }
        public bool ApplyScoresImmediately { get; set; }
    }
}
