//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMEVALUES
    {
        public short IdLineType { get; set; }
        public int IdGame { get; set; }
        public Nullable<int> VisitorOdds { get; set; }
        public Nullable<int> HomeOdds { get; set; }
        public Nullable<float> TotalOver { get; set; }
        public Nullable<int> OverOdds { get; set; }
        public Nullable<float> TotalUnder { get; set; }
        public Nullable<int> UnderOdds { get; set; }
        public Nullable<float> VisitorSpread { get; set; }
        public Nullable<int> VisitorSpreadOdds { get; set; }
        public Nullable<float> HomeSpread { get; set; }
        public Nullable<int> HomeSpreadOdds { get; set; }
        public Nullable<float> VisitorSpecial { get; set; }
        public Nullable<int> VisitorSpecialOdds { get; set; }
        public Nullable<float> HomeSpecial { get; set; }
        public Nullable<int> HomeSpecialOdds { get; set; }
        public bool SendToLS { get; set; }
        public bool HideGame { get; set; }
        public bool SyncSpread { get; set; }
        public bool SyncTotal { get; set; }
        public bool SyncML { get; set; }
        public bool BoldSpread { get; set; }
        public bool BoldTotal { get; set; }
        public bool BoldML { get; set; }
    }
}
