//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEDWAGERHEADER
    {
        public int IdWager { get; set; }
        public short IdLineType { get; set; }
        public int IdPlayer { get; set; }
        public short IdUser { get; set; }
        public short IdProfile { get; set; }
        public int IdWagerType { get; set; }
        public int IdCall { get; set; }
        public short PhoneLine { get; set; }
        public System.DateTime PlacedDate { get; set; }
        public decimal RiskAmount { get; set; }
        public decimal WinAmount { get; set; }
        public Nullable<System.DateTime> SettledDate { get; set; }
        public byte Stat { get; set; }
        public string Description { get; set; }
        public decimal MoneyChange { get; set; }
        public decimal OriginalWagerAmount { get; set; }
        public byte ChartPct { get; set; }
        public decimal OriginalRiskAmount { get; set; }
        public decimal OriginalWinAmount { get; set; }
        public byte Result { get; set; }
        public bool Graded { get; set; }
        public bool OpenPlay { get; set; }
        public bool FreePlay { get; set; }
        public byte RiskWin { get; set; }
        public float PointsPurchased { get; set; }
        public string CompleteDescription { get; set; }
        public Nullable<int> IfParent { get; set; }
        public Nullable<int> IfChild { get; set; }
        public bool IfParentGraded { get; set; }
        public Nullable<byte> IfParentResult { get; set; }
        public decimal IfBetRiskAmount { get; set; }
        public byte IfBetWagerType { get; set; }
        public int TicketNumber { get; set; }
        public bool EPOS { get; set; }
        public bool EPOSPaid { get; set; }
        public Nullable<int> IDCardHeader { get; set; }
        public byte WagerType { get; set; }
        public short IdBook { get; set; }
        public decimal TaxAmount { get; set; }
        public short CRRNumDetails { get; set; }
        public System.DateTime LastModification { get; set; }
    }
}
