//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITMeet
    {
        public string MeetingCode { get; set; }
        public bool Valid { get; set; }
        public Nullable<int> TrackID { get; set; }
        public Nullable<System.DateTime> RaceDate { get; set; }
        public short CurrentEasternBias { get; set; }
    }
}
