//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITMeet
    {
        public string MeetingCode { get; set; }
        public bool Valid { get; set; }
        public Nullable<int> TrackID { get; set; }
        public Nullable<System.DateTime> RaceDate { get; set; }
        public short CurrentEasternBias { get; set; }
    }
}
