//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitSetBetType
    {
        public int LimitSetID { get; set; }
        public byte BetType { get; set; }
        public decimal MaxStake { get; set; }
        public decimal MaxStakeOnline { get; set; }
        public decimal MaxPayoutOdds { get; set; }
        public decimal MaxPayoutCap { get; set; }
        public decimal AddPayoutOdds { get; set; }
        public bool ToteBet { get; set; }
        public decimal ToteThreshold { get; set; }
        public bool BetTypeEnabled { get; set; }
        public decimal Rebate { get; set; }
        public decimal RebateOnline { get; set; }
        public decimal MinStake { get; set; }
        public decimal MinStakeOnline { get; set; }
    }
}
