//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitSetBetType
    {
        public int LimitSetID { get; set; }
        public byte BetType { get; set; }
        public decimal MaxStake { get; set; }
        public decimal MaxStakeOnline { get; set; }
        public decimal MaxPayoutOdds { get; set; }
        public decimal MaxPayoutCap { get; set; }
        public decimal AddPayoutOdds { get; set; }
        public bool ToteBet { get; set; }
        public decimal ToteThreshold { get; set; }
        public bool BetTypeEnabled { get; set; }
        public decimal Rebate { get; set; }
        public decimal RebateOnline { get; set; }
        public decimal MinStake { get; set; }
        public decimal MinStakeOnline { get; set; }
    }
}
