//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitSet
    {
        public int LimitSetID { get; set; }
        public string LimitSetName { get; set; }
        public byte ParlayMaxSize { get; set; }
        public decimal MaxRaceWin { get; set; }
        public byte MaxRaceWinType { get; set; }
    }
}
