//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINETYPELINKS
    {
        public short IdLineTypeOut { get; set; }
        public short IdLineTypeIn { get; set; }
        public string IdSport { get; set; }
        public bool SpreadSync { get; set; }
        public bool SpreadOddsSync { get; set; }
        public bool TotalSync { get; set; }
        public bool TotalOddsSync { get; set; }
        public bool MoneyLineSync { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
        public byte LinkType { get; set; }
    }
}
