//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINETYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LINETYPE()
        {
            this.AGENT = new HashSet<AGENT>();
            this.AGENTLINETYPE = new HashSet<AGENTLINETYPE>();
        }
    
        public short IdLineType { get; set; }
        public string Description { get; set; }
        public bool FBBBSpreadSync { get; set; }
        public bool FBBBSpreadOddsSync { get; set; }
        public bool FBBBTotalSync { get; set; }
        public bool FBBBTotalOddsSync { get; set; }
        public bool FBBBMoneyLineSync { get; set; }
        public bool MLBMoneyLineSync { get; set; }
        public byte MLBIncrease { get; set; }
        public bool MLBRunSync { get; set; }
        public bool MLBRunOddsSync { get; set; }
        public bool MLBTotalSync { get; set; }
        public bool MLBTotalOddsSync { get; set; }
        public bool MUSpreadSync { get; set; }
        public bool MUSpreadOddsSync { get; set; }
        public bool MUTotalSync { get; set; }
        public bool MUTotalOddsSync { get; set; }
        public bool MUMoneyLineSync { get; set; }
        public byte NBAIncrease { get; set; }
        public bool NHLAmericanSync { get; set; }
        public bool NHLAmericanOddsSync { get; set; }
        public bool NHLCanadianSync { get; set; }
        public bool NHLCanadianOddsSync { get; set; }
        public bool NHLMoneyLineSync { get; set; }
        public bool NHLTotalSync { get; set; }
        public bool NHLTotalOddsSync { get; set; }
        public bool SOCGoalsSync { get; set; }
        public bool SOCGoalsOddsSync { get; set; }
        public bool SOCMoneyLineSync { get; set; }
        public bool SOCTotalSync { get; set; }
        public bool SOCTotalOddsSync { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENT> AGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTLINETYPE> AGENTLINETYPE { get; set; }
    }
}
