//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineSubscriber
    {
        public short IdSubscriber { get; set; }
        public string SubscriberName { get; set; }
        public short IdSubscriberType { get; set; }
        public short IdLineType { get; set; }
        public string ConfigurationData { get; set; }
        public bool Enabled { get; set; }
    }
}
