//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinePubQueue
    {
        public int IdQueue { get; set; }
        public System.DateTime QueueDateTime { get; set; }
        public short IdLineType { get; set; }
        public short IdLeague { get; set; }
        public string IdSport { get; set; }
        public int IdGame { get; set; }
        public int Play { get; set; }
    }
}
