//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinePubQueue
    {
        public int IdQueue { get; set; }
        public System.DateTime QueueDateTime { get; set; }
        public short IdLineType { get; set; }
        public short IdLeague { get; set; }
        public string IdSport { get; set; }
        public int IdGame { get; set; }
        public int Play { get; set; }
    }
}
