//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINETYPELINKS
    {
        public short IdLineTypeOut { get; set; }
        public short IdLineTypeIn { get; set; }
        public string IdSport { get; set; }
        public bool SpreadSync { get; set; }
        public bool SpreadOddsSync { get; set; }
        public bool TotalSync { get; set; }
        public bool TotalOddsSync { get; set; }
        public bool MoneyLineSync { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
        public byte LinkType { get; set; }
    }
}
