//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCK
    {
        public int LockID { get; set; }
        public byte LockType { get; set; }
        public int LockTypeID { get; set; }
        public short IdUser { get; set; }
        public int LogonSessionID { get; set; }
        public System.DateTime Acquired { get; set; }
    }
}
