//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxPayoutWork
    {
        public int RaceID { get; set; }
        public int AccountID { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal Stake { get; set; }
    }
}
