//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODDSBYSPORT
    {
        public short IdLineType { get; set; }
        public string IdSport { get; set; }
        public short Range { get; set; }
        public byte Line { get; set; }
        public int IdGameType { get; set; }
        public short OddsValue { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
