//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENTS
    {
        public short IdPayment { get; set; }
        public int IdPlayer { get; set; }
        public Nullable<byte> TransType { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public string RequestData { get; set; }
        public string ResponseData { get; set; }
        public Nullable<byte> PaymentType { get; set; }
        public string PaymentMethod { get; set; }
    }
}
