//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERL_DBD_TEST
    {
        public short COL_A { get; set; }
        public string COL_B { get; set; }
        public string COL_C { get; set; }
        public Nullable<System.DateTime> COL_D { get; set; }
    }
}
