//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERPROFILECUSTOMTEASER
    {
        public short IdProfile { get; set; }
        public int IdWagerType { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public byte TeaserSize { get; set; }
        public int Odds { get; set; }
        public int BuyHalf { get; set; }
        public int Buy1 { get; set; }
        public string Tie { get; set; }
        public Nullable<int> TieId { get; set; }
        public float NFLSide { get; set; }
        public float NFLTotal { get; set; }
        public float NBASide { get; set; }
        public float NBATotal { get; set; }
        public float CFBSide { get; set; }
        public float CFBTotal { get; set; }
        public float CBBSide { get; set; }
        public float CBBTotal { get; set; }
        public short MaxSide { get; set; }
        public short MaxTotal { get; set; }
        public bool DropHalfPoint { get; set; }
        public bool Special { get; set; }
        public bool Cancel { get; set; }
        public bool WaitForDetails { get; set; }
        public byte MaxOpenSpots { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
