//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERPROFILEPARLAYBASICSPORTSLOG
    {
        public int IdLog { get; set; }
        public short IdProfile { get; set; }
        public string idsport { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string Newvalue { get; set; }
        public short IdUser { get; set; }
        public System.DateTime Placeddate { get; set; }
        public short PhoneLine { get; set; }
        public string IP { get; set; }
    }
}
