//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERPROFILEPARLAYLIMITDETAIL
    {
        public short IdProfile { get; set; }
        public string IdSport { get; set; }
        public byte NumTeams { get; set; }
        public byte MaxGames { get; set; }
        public byte MaxDogs { get; set; }
        public Nullable<bool> UseFormula { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
        public byte MaxMoneyLines { get; set; }
    }
}
