//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERTRANSACTION
    {
        public int IdTransaction { get; set; }
        public int IdPlayer { get; set; }
        public System.DateTime PlacedDate { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public string Reference { get; set; }
        public decimal Fee { get; set; }
        public decimal Bonus { get; set; }
        public byte IdPaymentMethod { get; set; }
        public Nullable<byte> IdAdjustmentType { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
