//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERCREDITCARD
    {
        public int IdPlayer { get; set; }
        public short IdCreditCard { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string CCNumber { get; set; }
        public string CCDescription { get; set; }
        public string CCType { get; set; }
    }
}
