//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERPROFILESTRAIGHTLIMIT
    {
        public short IdProfile { get; set; }
        public string IdSport { get; set; }
        public float PointsPurchaseMax { get; set; }
        public short PriceHalfPoints { get; set; }
        public short JuiceDefault { get; set; }
        public Nullable<short> On3Surcharge { get; set; }
        public Nullable<short> Off3Surcharge { get; set; }
        public Nullable<short> On7Surcharge { get; set; }
        public Nullable<short> Off7Surcharge { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
