//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERCALLSLOG
    {
        public int IdCall { get; set; }
        public short PhoneLine { get; set; }
        public int IdPlayer { get; set; }
        public short IdUser { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<short> BetsTaked { get; set; }
        public string IP { get; set; }
        public bool Rec { get; set; }
        public string System { get; set; }
        public string URL { get; set; }
    }
}
