//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERPROFILELIMITS
    {
        public short IdProfileLimits { get; set; }
        public string ProfileName { get; set; }
        public string Notes { get; set; }
        public Nullable<short> AlternateProfile { get; set; }
        public Nullable<bool> AlternateEnable { get; set; }
        public Nullable<System.DateTime> LastModification { get; set; }
        public Nullable<short> LastModificationUser { get; set; }
    }
}
