//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERPROFILEGAMETYPE
    {
        public short IdProfile { get; set; }
        public int IdGameType { get; set; }
        public byte FreeHalfPoints { get; set; }
        public bool AllowON3NFL { get; set; }
        public bool AllowOFF3NFL { get; set; }
        public bool AllowON3CFB { get; set; }
        public bool AllowOFF3CFB { get; set; }
        public bool AllowON7NFL { get; set; }
        public bool AllowOFF7NFL { get; set; }
        public bool AllowON7CFB { get; set; }
        public bool AllowOFF7CFB { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
