//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERCREDITCARD
    {
        public int IdPlayer { get; set; }
        public short IdCreditCard { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string CCNumber { get; set; }
        public string CCDescription { get; set; }
        public string CCType { get; set; }
    }
}
