//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYERPROFILELIMITSDETAILS
    {
        public short IdProfileLimits { get; set; }
        public byte Online { get; set; }
        public int IdGameType { get; set; }
        public string IdSport { get; set; }
        public decimal Side { get; set; }
        public decimal Total { get; set; }
        public decimal MoneyLine { get; set; }
        public decimal Parlays { get; set; }
        public decimal Teasers { get; set; }
        public decimal IfBets { get; set; }
        public decimal Reverses { get; set; }
        public decimal Related { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
