//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoolPayout
    {
        public int RaceID { get; set; }
        public byte PoolType { get; set; }
        public string Entries { get; set; }
        public byte NumCorrect { get; set; }
        public decimal Payoff { get; set; }
    }
}
