//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductCode { get; set; }
        public double ShippingWeight { get; set; }
        public double ShippingLength { get; set; }
        public double ShippingWidth { get; set; }
        public double ShippingHeight { get; set; }
        public double UnitCost { get; set; }
        public byte PerOrder { get; set; }
    }
}
