//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductCode { get; set; }
        public double ShippingWeight { get; set; }
        public double ShippingLength { get; set; }
        public double ShippingWidth { get; set; }
        public double ShippingHeight { get; set; }
        public double UnitCost { get; set; }
        public byte PerOrder { get; set; }
    }
}
