//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceTicketBatchHeader
    {
        public int BatchID { get; set; }
        public byte BatchType { get; set; }
        public System.DateTime BatchDateTime { get; set; }
        public bool BatchReady { get; set; }
    }
}
