//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceTicketType
    {
        public byte TicketType { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public byte NumLegs { get; set; }
        public byte BaseTicketType { get; set; }
        public string BaseShortDesc { get; set; }
    }
}
