//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceTicketBatchHeader
    {
        public int BatchID { get; set; }
        public byte BatchType { get; set; }
        public System.DateTime BatchDateTime { get; set; }
        public bool BatchReady { get; set; }
    }
}
