//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceTicketBatchDetail
    {
        public int BatchID { get; set; }
        public int TicketID { get; set; }
        public byte BatchType { get; set; }
        public int WagerID { get; set; }
        public int AccountID { get; set; }
        public decimal TotalStake { get; set; }
        public decimal WinAmount { get; set; }
        public decimal RefundAmount { get; set; }
        public System.DateTime SettleDate { get; set; }
    }
}
