//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebateHeader
    {
        public int RebateID { get; set; }
        public int AccountID { get; set; }
        public System.DateTime RebatePaidDate { get; set; }
        public System.DateTime CutoffDate { get; set; }
        public decimal RebateAmount { get; set; }
        public decimal ExchangeRate { get; set; }
        public string CurrencyCode { get; set; }
    }
}
