//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebateDetail
    {
        public int RebateID { get; set; }
        public byte BetType { get; set; }
        public byte UIType { get; set; }
        public decimal Volume { get; set; }
        public decimal Rebate { get; set; }
        public decimal WinLoss { get; set; }
    }
}
