//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebateDetail
    {
        public int RebateID { get; set; }
        public byte BetType { get; set; }
        public byte UIType { get; set; }
        public decimal Volume { get; set; }
        public decimal Rebate { get; set; }
        public decimal WinLoss { get; set; }
    }
}
