//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebateHeader
    {
        public int RebateID { get; set; }
        public int AccountID { get; set; }
        public System.DateTime RebatePaidDate { get; set; }
        public System.DateTime CutoffDate { get; set; }
        public decimal RebateAmount { get; set; }
        public decimal ExchangeRate { get; set; }
        public string CurrencyCode { get; set; }
    }
}
