//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportsOptionsGroup
    {
        public int SportsOptionsGroupId { get; set; }
        public int id { get; set; }
        public int display_order { get; set; }
        public int league_id { get; set; }
        public int subleague_id { get; set; }
        public string date { get; set; }
        public int ordering { get; set; }
        public string description { get; set; }
        public int scheduleId { get; set; }
    }
}
