//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportsOptionsLeague
    {
        public int SportsOptionsLeagueId { get; set; }
        public int id { get; set; }
        public int league_id { get; set; }
        public int sport_id { get; set; }
        public int periods { get; set; }
        public int time_per_period { get; set; }
        public int half_time_minutes { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public string covers_league { get; set; }
        public string covers_sport { get; set; }
        public bool prop { get; set; }
        public bool ml { get; set; }
        public int scheduleId { get; set; }
    }
}
