//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMPREFERENCESDEFAULT
    {
        public short IdBook { get; set; }
        public byte DefaultActionPoints { get; set; }
        public short DefaultCurrency { get; set; }
        public decimal DefaultMaxWager { get; set; }
        public decimal DefaultMaxWagerOnline { get; set; }
        public decimal DefaultMinWager { get; set; }
        public decimal DefaultMinWagerOnline { get; set; }
        public string DefaultNHLLine { get; set; }
        public string DefaultMLBLine { get; set; }
        public short DefaultLineType { get; set; }
        public string DefaultLineStyle { get; set; }
        public byte DefaultOffice { get; set; }
        public short DefaultProfile { get; set; }
        public decimal DefaultSettleAmount { get; set; }
        public bool DefaultShowInTicker { get; set; }
        public byte DefaultSoftLimit { get; set; }
        public Nullable<int> DefaultAgent { get; set; }
        public Nullable<short> DefaultGroup { get; set; }
        public short DefaultPlayertype { get; set; }
        public short DefaultFlagType { get; set; }
        public bool DefaultMaster { get; set; }
        public string DefaultEnable { get; set; }
        public bool DefaultOnline { get; set; }
        public bool DefaultEnableSports { get; set; }
        public bool DefaultEnableCasino { get; set; }
        public bool DefaultEnableHorses { get; set; }
        public bool DefaultEnableCards { get; set; }
        public short DefaultChart { get; set; }
        public short DefaultMasterChart { get; set; }
        public string DefaultBonusPointsStatus { get; set; }
        public System.DateTime DefaultBonusPointsStart { get; set; }
        public System.DateTime DefaultBonusPointsExpire { get; set; }
        public string DefaultFlagMessage { get; set; }
        public string DefaultOnlineMessage { get; set; }
        public int IdTimeZone { get; set; }
        public byte IdLanguage { get; set; }
        public string ScheduleStyle { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
        public short DefaultProfileLimit { get; set; }
    }
}
