//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMPREFERENCESCLIENT
    {
        public bool DisableCreditFeatures { get; set; }
        public byte GameCuttOffTime { get; set; }
        public bool HideOTBGames { get; set; }
        public byte NoActionLimit { get; set; }
        public bool PhoneRequired { get; set; }
        public bool PlayerPasswordUsage { get; set; }
        public bool ShowDefaultLine { get; set; }
        public bool SoundRecording { get; set; }
        public bool UsePhoneDefault { get; set; }
        public byte WagerTimeLimit { get; set; }
        public bool SimultaneousLogin { get; set; }
        public bool UseRecManager { get; set; }
        public short Threshold { get; set; }
        public short PrecallTimer { get; set; }
        public bool IfBetsNUI { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
