//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMCHANGEDLINES
    {
        public int IdSystemChangedLines { get; set; }
        public Nullable<short> IdLineType { get; set; }
        public string IdSport { get; set; }
        public Nullable<short> IdUser { get; set; }
        public Nullable<int> IdGame { get; set; }
        public Nullable<int> TeamNumber { get; set; }
        public Nullable<byte> ColumnNumber { get; set; }
        public string ChangeValue { get; set; }
        public Nullable<short> PhoneLine { get; set; }
        public Nullable<System.DateTime> PlacedDate { get; set; }
        public Nullable<int> Play { get; set; }
        public Nullable<int> IdAgent { get; set; }
    }
}
