//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMBETRADARCONFIG
    {
        public short RefreshRate { get; set; }
        public string FilesPath { get; set; }
        public int idGameType { get; set; }
        public int idLineType { get; set; }
        public bool ImportOdds { get; set; }
        public bool ImportScores { get; set; }
        public bool AutomaticGrade { get; set; }
        public short ImportCSasProps { get; set; }
        public System.DateTime LastModification { get; set; }
    }
}
