//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMDICTIONARY
    {
        public short IdLanguage { get; set; }
        public string IdMessage { get; set; }
        public string Page { get; set; }
        public string Message { get; set; }
    }
}
