//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMPROCESSFLAG
    {
        public string ProcessName { get; set; }
        public short IdUser { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<short> PhoneLine { get; set; }
        public string IP { get; set; }
    }
}
