//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMPREFERENCESCLIENT
    {
        public bool DisableCreditFeatures { get; set; }
        public byte GameCuttOffTime { get; set; }
        public bool HideOTBGames { get; set; }
        public byte NoActionLimit { get; set; }
        public bool PhoneRequired { get; set; }
        public bool PlayerPasswordUsage { get; set; }
        public bool ShowDefaultLine { get; set; }
        public bool SoundRecording { get; set; }
        public bool UsePhoneDefault { get; set; }
        public byte WagerTimeLimit { get; set; }
        public bool SimultaneousLogin { get; set; }
        public bool UseRecManager { get; set; }
        public short Threshold { get; set; }
        public short PrecallTimer { get; set; }
        public bool IfBetsNUI { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
    }
}
