//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMVERSIONINFO
    {
        public string DbVersion { get; set; }
        public short CustoID { get; set; }
        public bool EposEnabled { get; set; }
        public bool HorseEnabled { get; set; }
        public bool BonusPointsEnabled { get; set; }
        public bool CasinoEnabled { get; set; }
        public bool CardsEnabled { get; set; }
        public byte DaysBeforeExpirationWarning { get; set; }
        public bool UseWindowsUser { get; set; }
        public Nullable<System.DateTime> LastArchivingDate { get; set; }
        public bool GameSyncEnabled { get; set; }
        public bool UsePassEncrypt { get; set; }
        public System.DateTime LastModification { get; set; }
        public string LastModificationUser { get; set; }
    }
}
