//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMPREFERENCESMANAGER
    {
        public string ActionColumnDisplay { get; set; }
        public short DaysBeforeInactive { get; set; }
        public bool DefaultAmericanEven { get; set; }
        public short DefaultBook { get; set; }
        public int DefaultGameType { get; set; }
        public decimal DefaultLineHistory { get; set; }
        public short DefaultLineType { get; set; }
        public int DefaultPeriodGameType { get; set; }
        public bool EnabledBonusPoints { get; set; }
        public bool EnabledJuiceChart { get; set; }
        public byte GamesRefresh { get; set; }
        public byte HistoryShowDays { get; set; }
        public short ListMaxItems { get; set; }
        public bool LockDateTransac { get; set; }
        public bool LockAccountOpened { get; set; }
        public bool NewGamesOffBoard { get; set; }
        public bool RefreshAction { get; set; }
        public bool RefreshLines { get; set; }
        public bool SendAmericanLineToDBS { get; set; }
        public bool ShowActionOptions { get; set; }
        public string SoundServerPath { get; set; }
        public string SoundLocalPath { get; set; }
        public bool UseDecimals { get; set; }
        public byte UseLeagues { get; set; }
        public bool UseNewSynch { get; set; }
        public byte WeekStartsOn { get; set; }
        public Nullable<bool> MoveCloseGames { get; set; }
        public bool ChartDefaultAll { get; set; }
        public bool UseRelatedLimit { get; set; }
        public bool UseSplitAgentComm { get; set; }
        public bool UseSplitPerHead { get; set; }
        public bool UseTaxes { get; set; }
        public bool UseLineSyncByGame { get; set; }
        public bool SyncRunlineAsSpread { get; set; }
        public bool SyncGoalLineAsSpread { get; set; }
        public bool DecimalsChart { get; set; }
        public bool APCountTie { get; set; }
        public bool UseRelatedLimitsOnTeasers { get; set; }
        public System.DateTime LastModification { get; set; }
        public short LastModificationUser { get; set; }
        public bool IncludeAPInChart { get; set; }
    }
}
