//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMCHANGEDLINESLOG
    {
        public int IdSystemChangedLines { get; set; }
        public Nullable<short> IdLineType { get; set; }
        public string IdSport { get; set; }
        public Nullable<short> IdUser { get; set; }
        public Nullable<int> IdGame { get; set; }
        public Nullable<int> TeamNumber { get; set; }
        public Nullable<byte> ColumnNumber { get; set; }
        public string ChangeValue { get; set; }
        public Nullable<short> PhoneLine { get; set; }
        public Nullable<System.DateTime> PlacedDate { get; set; }
        public Nullable<int> Play { get; set; }
        public Nullable<int> IdAgent { get; set; }
    }
}
