//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoUTStatusChange
    {
        public int id { get; set; }
        public string SiteId { get; set; }
        public string RunId { get; set; }
        public System.DateTime MessageTime { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public string Action { get; set; }
        public string EventId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
        public Nullable<long> MTP { get; set; }
        public string SourceIds { get; set; }
    }
}
