//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPlaceBetAlg
    {
        public int TaceoPlaceBetAlgId { get; set; }
        public int WagerId { get; set; }
        public string GuidSender { get; set; }
        public int BetAmount { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<decimal> PinnBetAmount { get; set; }
        public Nullable<decimal> AlgWinRatio { get; set; }
        public Nullable<decimal> AlgRoiBet { get; set; }
        public Nullable<decimal> AlgRoiOverAll { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> WagerDetailId { get; set; }
    }
}
