//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoUTRace
    {
        public int id { get; set; }
        public int EventId { get; set; }
        public int RaceNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public int NumRunners { get; set; }
        public string Finish { get; set; }
        public string PoolList { get; set; }
        public bool Current { get; set; }
        public string RaceType { get; set; }
        public string Distance { get; set; }
        public string Age { get; set; }
        public decimal Claim { get; set; }
        public string Conditions { get; set; }
        public string ExtensionData { get; set; }
        public string Live { get; set; }
        public bool Odds { get; set; }
        public bool Program { get; set; }
        public decimal Purse { get; set; }
        public int RaceId { get; set; }
        public string Sex { get; set; }
        public string Surface { get; set; }
        public string TrackType { get; set; }
    }
}
