//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoWagerLog
    {
        public int IdLog { get; set; }
        public int IdPlayer { get; set; }
        public int IdCall { get; set; }
        public System.DateTime DatePlaced { get; set; }
        public string WagerDescription { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> IdGameFirst { get; set; }
        public string IdGamesAll { get; set; }
        public string IdGamesChanged { get; set; }
        public string LogReason { get; set; }
    }
}
