//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoImportedTotals
    {
        public int underadjust { get; set; }
        public int overadjust { get; set; }
        public string units { get; set; }
        public int points { get; set; }
        public int lineid { get; set; }
        public int tiTotalsId { get; set; }
    }
}
