//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoLineConverterSportConfig
    {
        public int TaceoLineConverterSportConfigId { get; set; }
        public int IdLineTypeSrc { get; set; }
        public int IdLineTypeDst { get; set; }
        public string LineTypeSrc { get; set; }
        public string LineTypeDst { get; set; }
        public string SportId { get; set; }
        public int Period { get; set; }
        public int Play { get; set; }
        public bool Active { get; set; }
        public decimal Edge { get; set; }
        public bool Sync { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public System.DateTime LastChanged { get; set; }
    }
}
