//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMoneyLine
    {
        public int TaceoPinnMoneyLineId { get; set; }
        public decimal awayPrice { get; set; }
        public decimal homePrice { get; set; }
        public Nullable<decimal> drawPrice { get; set; }
        public int lineid { get; set; }
    }
}
