//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPasswordRecovery
    {
        public int IdPlayer { get; set; }
        public string Email { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime DateTimeRequest { get; set; }
        public string Md5 { get; set; }
        public bool IsReset { get; set; }
        public Nullable<System.DateTime> DateTimeReset { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
