//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoApiPostTransActionLog
    {
        public int IdApiTransAction { get; set; }
        public System.DateTime DateTime { get; set; }
        public string CustomerId { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string c { get; set; }
        public string Comment { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
    }
}
