//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoMonitorSetting
    {
        public int TaceoMonitorSettingId { get; set; }
        public System.DateTime LastStarted { get; set; }
        public System.DateTime LastEnded { get; set; }
        public string DefaultFromEmail { get; set; }
        public string DefaultMailServer { get; set; }
        public string DefaultDBconn { get; set; }
        public int LastVigorChangedId { get; set; }
        public Nullable<int> TaceoPlaceBetAlgId { get; set; }
    }
}
