//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMatchSport
    {
        public int TaceoPinnMatchSportId { get; set; }
        public string tidSport { get; set; }
        public Nullable<int> pidSport { get; set; }
        public string pSport { get; set; }
        public Nullable<int> soidSport { get; set; }
        public string soSport { get; set; }
        public bool syncPinnSport { get; set; }
        public bool syncSoSport { get; set; }
    }
}
