//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoDomainNames
    {
        public int IdDomain { get; set; }
        public string DomainName { get; set; }
        public string Theme { get; set; }
        public string Tel { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> IdBook { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<bool> Logo { get; set; }
        public Nullable<bool> HasLiveCasino { get; set; }
        public Nullable<bool> HasLiveBetting { get; set; }
        public Nullable<bool> HasBanners { get; set; }
        public string LiveBettingUrl { get; set; }
    }
}
