//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoUTEvent
    {
        public int id { get; set; }
        public string EventCode { get; set; }
        public string EventType { get; set; }
        public string EventName { get; set; }
        public string TrackCode { get; set; }
        public string TrackName { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string TrackType { get; set; }
        public string EventStatus { get; set; }
        public string RaceList { get; set; }
        public Nullable<System.DateTime> EventInfo { get; set; }
        public Nullable<decimal> BreakTo { get; set; }
        public string Channel { get; set; }
        public string CurrencyId { get; set; }
        public string EventClass { get; set; }
        public Nullable<bool> Parlay { get; set; }
        public string RunId { get; set; }
        public string TrackCondition { get; set; }
        public string TurfTrack { get; set; }
    }
}
