//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnPeriod
    {
        public int TaceoPinnPeriodId { get; set; }
        public int sportId { get; set; }
        public string sport { get; set; }
        public int leagueId { get; set; }
        public string league { get; set; }
        public int eventId { get; set; }
        public int lineId { get; set; }
        public int number { get; set; }
        public string description { get; set; }
        public string cutOffDateTime { get; set; }
        public decimal maxSpread { get; set; }
        public decimal maxTotal { get; set; }
        public decimal maxML { get; set; }
        public decimal maxTeamTotal { get; set; }
    }
}
