//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoImportedLeague
    {
        public string leaguename { get; set; }
        public int leagueid { get; set; }
        public string sportname { get; set; }
        public int sportstypeid { get; set; }
        public int lineid { get; set; }
        public int tiLeagueId { get; set; }
    }
}
