//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoInternalReportsLog
    {
        public int IdLog { get; set; }
        public int IdUser { get; set; }
        public string Action { get; set; }
        public string ParamsUsed { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string IpAddress { get; set; }
    }
}
