//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoLineConverterSportConfig
    {
        public int TaceoLineConverterSportConfigId { get; set; }
        public int IdLineTypeSrc { get; set; }
        public int IdLineTypeDst { get; set; }
        public string LineTypeSrc { get; set; }
        public string LineTypeDst { get; set; }
        public string SportId { get; set; }
        public int Period { get; set; }
        public int Play { get; set; }
        public bool Active { get; set; }
        public decimal Edge { get; set; }
        public bool Sync { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public System.DateTime LastChanged { get; set; }
    }
}
