//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoUTUpdate
    {
        public int id { get; set; }
        public string SiteId { get; set; }
        public string RunId { get; set; }
        public System.DateTime MessageTime { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public string Type { get; set; }
        public string Data { get; set; }
        public string Section { get; set; }
        public string Group { get; set; }
        public string Track { get; set; }
        public bool Post { get; set; }
        public string EventId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public string Source { get; set; }
        public string SourceIds { get; set; }
    }
}
