//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSyncDGSdbTestingDB
    {
        public int IdTaceoSyncDGSdbTestingDB { get; set; }
        public System.DateTime SportLastChanged { get; set; }
        public System.DateTime LeagueLastChanged { get; set; }
        public System.DateTime TeamLastChanged { get; set; }
        public System.DateTime GameLastChanged { get; set; }
        public int LastChangedLineId { get; set; }
    }
}
