//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoGroup_Header
    {
        public int TaceoSoGroup_HeaderId { get; set; }
        public int GroupId { get; set; }
        public int group_display_order { get; set; }
        public int display_order { get; set; }
        public string text { get; set; }
    }
}
