//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoBetTicker
    {
        public int IdBetTicker { get; set; }
        public int IdAgent { get; set; }
        public string PlayerList { get; set; }
        public bool Audio { get; set; }
        public int UpdateFreq { get; set; }
        public bool Visual { get; set; }
        public int RiskAmount { get; set; }
        public string TitleEmail { get; set; }
        public string SendTo { get; set; }
        public bool Active { get; set; }
        public bool Ticker { get; set; }
        public bool EndOfDay { get; set; }
        public int IdWager { get; set; }
        public Nullable<System.DateTime> LastCheck { get; set; }
        public Nullable<System.DateTime> LastSend { get; set; }
        public bool Deleted { get; set; }
    }
}
