//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoEPOSECSALog
    {
        public int IdLog { get; set; }
        public System.DateTime DateTimeSend { get; set; }
        public string FileName { get; set; }
        public Nullable<int> IdLocation { get; set; }
        public string TransactionId { get; set; }
        public string Type { get; set; }
    }
}
