//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoImportedTeam
    {
        public string pitcher { get; set; }
        public string visitinghomedraw { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public int rotnum { get; set; }
        public int lineid { get; set; }
        public int tiTeamId { get; set; }
    }
}
