//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPlaceBetAlg
    {
        public int TaceoPlaceBetAlgId { get; set; }
        public int WagerId { get; set; }
        public string GuidSender { get; set; }
        public int BetAmount { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<decimal> PinnBetAmount { get; set; }
        public Nullable<decimal> AlgWinRatio { get; set; }
        public Nullable<decimal> AlgRoiBet { get; set; }
        public Nullable<decimal> AlgRoiOverAll { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> WagerDetailId { get; set; }
    }
}
