//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPlayerLoginLog
    {
        public int IdCall { get; set; }
        public string IpAddress { get; set; }
        public Nullable<long> FingerPrint { get; set; }
        public Nullable<System.DateTime> PlacedDate { get; set; }
        public string DomainName { get; set; }
        public string UserAgent { get; set; }
        public Nullable<long> IpNum { get; set; }
    }
}
