//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnTotalPoints
    {
        public int TaceoPinnTotalPointsId { get; set; }
        public Nullable<int> altLineId { get; set; }
        public decimal points { get; set; }
        public decimal overPrice { get; set; }
        public decimal underPrice { get; set; }
        public int lineId { get; set; }
        public Nullable<int> homeId { get; set; }
        public Nullable<int> awayId { get; set; }
    }
}
