//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoGroup_Header
    {
        public int TaceoSoGroup_HeaderId { get; set; }
        public int GroupId { get; set; }
        public int group_display_order { get; set; }
        public int display_order { get; set; }
        public string text { get; set; }
    }
}
