//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoEvent_Team_Score
    {
        public int TaceoSoEvent_Team_ScoreId { get; set; }
        public int score { get; set; }
        public int period_score { get; set; }
        public int event_number { get; set; }
        public int number { get; set; }
        public string time_stamp { get; set; }
    }
}
