//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMatchTeams
    {
        public int IdTaceoPinnMatchTeamid { get; set; }
        public string dgsSportId { get; set; }
        public int dgsLeagueId { get; set; }
        public string dgsLeague { get; set; }
        public string dgsTeamName { get; set; }
        public Nullable<int> pinnSportId { get; set; }
        public Nullable<int> pinnLeagueId { get; set; }
        public string pinnLeague { get; set; }
        public string pinnTeamName { get; set; }
    }
}
