//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoDomainNames
    {
        public int IdDomain { get; set; }
        public string DomainName { get; set; }
        public string Theme { get; set; }
        public string Tel { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> IdBook { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<bool> Logo { get; set; }
        public Nullable<bool> HasLiveCasino { get; set; }
        public Nullable<bool> HasLiveBetting { get; set; }
        public Nullable<bool> HasBanners { get; set; }
        public string LiveBettingUrl { get; set; }
    }
}
