//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoErrorLog
    {
        public int IdErrorLog { get; set; }
        public string Client { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
