//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoImportedLine
    {
        public int periodnum { get; set; }
        public string perioddesc { get; set; }
        public int lineid { get; set; }
        public Nullable<System.DateTime> insertdt { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> eventdt { get; set; }
        public int gameid { get; set; }
        public int tiLineId { get; set; }
    }
}
