//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoUTPool
    {
        public int id { get; set; }
        public int RaceId { get; set; }
        public string PoolId { get; set; }
        public string PoolName { get; set; }
        public decimal WagerMin { get; set; }
        public decimal WagerMax { get; set; }
        public decimal Size { get; set; }
    }
}
