//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoHideGame
    {
        public int IdHideGame { get; set; }
        public Nullable<int> IdGame { get; set; }
        public Nullable<bool> HideGame { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<short> IdLineType { get; set; }
    }
}
