//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoAgentWebLog
    {
        public int IdLog { get; set; }
        public int IdAgent { get; set; }
        public Nullable<int> IdSubAgent { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Action { get; set; }
        public string IpAddress { get; set; }
        public string FingerPrint { get; set; }
        public string Type { get; set; }
        public string UserAgent { get; set; }
    }
}
