//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMatchLeagueASL
    {
        public int TaceoPinnMatchLeagueASLid { get; set; }
        public Nullable<int> PinnIdLeague { get; set; }
        public string PinnLeague { get; set; }
        public int ASLidLeague { get; set; }
        public string ASLLeague { get; set; }
        public bool Sync { get; set; }
        public int ASLuserId { get; set; }
    }
}
