//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoTeamMatchBC
    {
        public int TaceoTeamMatchBCId { get; set; }
        public int IdTeam { get; set; }
        public string IdSport { get; set; }
        public string TeamName { get; set; }
        public string LongName { get; set; }
        public string IdSportBC { get; set; }
        public string TeamNameBC { get; set; }
    }
}
