//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnLeague
    {
        public int TaceoPinnLeagueId { get; set; }
        public string sport { get; set; }
        public int sportId { get; set; }
        public int leagueId { get; set; }
        public string league { get; set; }
        public bool feedContent { get; set; }
        public string last { get; set; }
        public bool sync { get; set; }
    }
}
