//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMatchLeagueASL
    {
        public int TaceoPinnMatchLeagueASLid { get; set; }
        public Nullable<int> PinnIdLeague { get; set; }
        public string PinnLeague { get; set; }
        public int ASLidLeague { get; set; }
        public string ASLLeague { get; set; }
        public bool Sync { get; set; }
        public int ASLuserId { get; set; }
    }
}
