//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoEvent_Score
    {
        public int TaceoSoEvent_ScoreId { get; set; }
        public int number { get; set; }
        public int period { get; set; }
        public string timer { get; set; }
        public string status { get; set; }
        public string time_stamp { get; set; }
    }
}
