//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoEvent_Score
    {
        public int TaceoSoEvent_ScoreId { get; set; }
        public int number { get; set; }
        public int period { get; set; }
        public string timer { get; set; }
        public string status { get; set; }
        public string time_stamp { get; set; }
    }
}
