//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoLineboardNotification
    {
        public int IdNotification { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateTimeNotification { get; set; }
        public Nullable<bool> Cleared { get; set; }
        public Nullable<System.DateTime> DateTimeCleared { get; set; }
        public Nullable<int> UserCleared { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
    }
}
