//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMatchSport
    {
        public int TaceoPinnMatchSportId { get; set; }
        public string tidSport { get; set; }
        public Nullable<int> pidSport { get; set; }
        public string pSport { get; set; }
        public Nullable<int> soidSport { get; set; }
        public string soSport { get; set; }
        public bool syncPinnSport { get; set; }
        public bool syncSoSport { get; set; }
    }
}
