//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnEvent
    {
        public int TaceoPinnEventId { get; set; }
        public string startDateTime { get; set; }
        public int eventId { get; set; }
        public bool IsLive { get; set; }
        public string status { get; set; }
        public Nullable<int> drawRotNum { get; set; }
        public string homeTeamName { get; set; }
        public string homeTeamType { get; set; }
        public Nullable<int> homeTeamRotNum { get; set; }
        public Nullable<int> homeTeamScore { get; set; }
        public string awayTeamName { get; set; }
        public string awayTeamType { get; set; }
        public Nullable<int> awayTeamRotNum { get; set; }
        public Nullable<int> awayTeamScore { get; set; }
        public int sportId { get; set; }
        public string sport { get; set; }
        public int leagueId { get; set; }
        public string league { get; set; }
        public string awayPitcher { get; set; }
        public string homePitcher { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
