//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMoneyLine
    {
        public int TaceoPinnMoneyLineId { get; set; }
        public decimal awayPrice { get; set; }
        public decimal homePrice { get; set; }
        public Nullable<decimal> drawPrice { get; set; }
        public int lineid { get; set; }
    }
}
