//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMatchLeague
    {
        public int TaceoPinnMatchLeagueId { get; set; }
        public int TidLeague { get; set; }
        public string TLeague { get; set; }
        public Nullable<int> PidLeague { get; set; }
        public string PLeague { get; set; }
        public Nullable<int> SoidLeague { get; set; }
        public string SoLeague { get; set; }
        public bool syncPinn { get; set; }
        public bool syncSo { get; set; }
    }
}
