//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoTeam
    {
        public int TaceoSoTeamId { get; set; }
        public int number { get; set; }
        public int ORN { get; set; }
        public int event_number { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string nickname { get; set; }
        public string abbr { get; set; }
        public int covers_id { get; set; }
        public int score { get; set; }
        public int period { get; set; }
        public string record { get; set; }
        public string ranking { get; set; }
        public int event_id { get; set; }
    }
}
