//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoTeam
    {
        public int TaceoSoTeamId { get; set; }
        public int number { get; set; }
        public int ORN { get; set; }
        public int event_number { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string nickname { get; set; }
        public string abbr { get; set; }
        public int covers_id { get; set; }
        public int score { get; set; }
        public int period { get; set; }
        public string record { get; set; }
        public string ranking { get; set; }
        public int event_id { get; set; }
    }
}
