//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoRasPicks
    {
        public int TaceoRasPicksId { get; set; }
        public string SportId { get; set; }
        public int TeamNumber { get; set; }
        public string TeamName { get; set; }
        public string Points { get; set; }
        public System.DateTime GameDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
