//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoErrorLog
    {
        public int IdErrorLog { get; set; }
        public string Client { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
