//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoImportedLine
    {
        public int periodnum { get; set; }
        public string perioddesc { get; set; }
        public int lineid { get; set; }
        public Nullable<System.DateTime> insertdt { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> eventdt { get; set; }
        public int gameid { get; set; }
        public int tiLineId { get; set; }
    }
}
