//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoTeamMatchBC
    {
        public int TaceoTeamMatchBCId { get; set; }
        public int IdTeam { get; set; }
        public string IdSport { get; set; }
        public string TeamName { get; set; }
        public string LongName { get; set; }
        public string IdSportBC { get; set; }
        public string TeamNameBC { get; set; }
    }
}
