//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPinnMatchSportASL
    {
        public int TaceoPinnMatchSportASLid { get; set; }
        public int ASLuserId { get; set; }
        public string ASLidSport { get; set; }
        public Nullable<int> PinnIdSport { get; set; }
        public string PinnSport { get; set; }
        public bool SyncSport { get; set; }
    }
}
