//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoLineNotification
    {
        public int IdDelayNotification { get; set; }
        public System.DateTime Notification { get; set; }
        public System.DateTime GameDateTime { get; set; }
        public bool Auto { get; set; }
        public bool IsHidden { get; set; }
        public bool Done { get; set; }
        public string Description { get; set; }
        public Nullable<int> HoursBeforeGame { get; set; }
        public int IdLineType { get; set; }
        public int IdGame { get; set; }
        public int IdUser { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Deleted { get; set; }
        public string IdSport { get; set; }
        public string LineType { get; set; }
    }
}
