//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoSoEvent
    {
        public int TaceoSoEventId { get; set; }
        public int id { get; set; }
        public int number { get; set; }
        public int ORN { get; set; }
        public int league_id { get; set; }
        public int subleague_id { get; set; }
        public string scheduled_date { get; set; }
        public string scheduled_time { get; set; }
        public string start_date { get; set; }
        public string start_time { get; set; }
    }
}
