//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoBookMessage
    {
        public int IdBook { get; set; }
        public string MessageHeader { get; set; }
        public string MessageBody { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> PlacedDate { get; set; }
        public Nullable<int> IdUser { get; set; }
    }
}
