//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaceoPlayerRights
    {
        public int IdPlayer { get; set; }
        public Nullable<bool> Pickem { get; set; }
        public Nullable<int> LastModificationUser { get; set; }
        public Nullable<System.DateTime> LastModification { get; set; }
    }
}
