//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeaserBtnDetail
    {
        public short IdProfile { get; set; }
        public short IdTeaserBtn { get; set; }
        public byte NumTeams { get; set; }
        public int IdWagerType { get; set; }
        public string TeaserName { get; set; }
    }
}
