//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeaserBtnMain
    {
        public short IdProfile { get; set; }
        public short IdTeaserBtn { get; set; }
        public string BtnCaption { get; set; }
        public byte BtnIndex { get; set; }
    }
}
