//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETTEMPLATE
    {
        public int TicketTemplateID { get; set; }
        public string Description { get; set; }
        public string TicketTemplate1 { get; set; }
    }
}
