//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHoldRelease
    {
        public int TicketNumber { get; set; }
        public int ReleaseID { get; set; }
        public int ManagerID { get; set; }
        public System.DateTime HoldDateTime { get; set; }
        public string HoldReason { get; set; }
        public int ReleaseManagerID { get; set; }
        public System.DateTime ReleaseDateTime { get; set; }
        public string ReleaseReason { get; set; }
    }
}
