//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKERCONFIGURATION
    {
        public short IdUser { get; set; }
        public short RefreshFrecuency { get; set; }
        public bool WagerPosition { get; set; }
        public bool ShowNFL { get; set; }
        public bool ShowCFB { get; set; }
        public bool ShowNBA { get; set; }
        public bool ShowCBB { get; set; }
        public bool ShowMLB { get; set; }
        public bool ShowNHL { get; set; }
        public bool ShowMU { get; set; }
        public bool ShowSOC { get; set; }
        public bool ShowESOC { get; set; }
        public bool ShowTNT { get; set; }
        public bool ShowPROP { get; set; }
        public bool ShowRAC { get; set; }
        public bool StraightBets { get; set; }
        public bool Parlays { get; set; }
        public bool Teasers { get; set; }
        public bool IfBets { get; set; }
        public bool Reverses { get; set; }
        public bool ActionPoints { get; set; }
        public bool LocalWagers { get; set; }
        public bool OnlineWagers { get; set; }
        public bool Games { get; set; }
        public bool Halves { get; set; }
        public bool Quarters { get; set; }
        public bool Periods { get; set; }
        public bool NormalPlayers { get; set; }
        public bool MasterPlayers { get; set; }
        public bool CreditPlayers { get; set; }
        public bool CashPlayers { get; set; }
        public bool SearchPlayer { get; set; }
        public Nullable<int> IdPlayer { get; set; }
        public bool SearchAgent { get; set; }
        public Nullable<int> IdAgent { get; set; }
        public bool SearchPlayerType { get; set; }
        public Nullable<short> IdPlayerType { get; set; }
        public bool SearchBook { get; set; }
        public Nullable<short> IdBook { get; set; }
        public bool SearchProfile { get; set; }
        public Nullable<short> IdProfile { get; set; }
        public bool SearchOffice { get; set; }
        public Nullable<short> IdOffice { get; set; }
        public bool SearchGrouping { get; set; }
        public Nullable<short> IdGrouping { get; set; }
        public bool SearchCurrency { get; set; }
        public Nullable<short> IdCurrency { get; set; }
        public bool DisplayHoldBets { get; set; }
    }
}
