//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TillTransact
    {
        public int TillTransactID { get; set; }
        public int ActiveTillID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime TransactDateTime { get; set; }
        public decimal TransactAmount { get; set; }
        public Nullable<int> TicketNumber { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<int> RefillID { get; set; }
        public Nullable<short> IdUser { get; set; }
        public string CurrCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal CurrencyDiff { get; set; }
        public System.DateTime OpDate { get; set; }
    }
}
