//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERLOGONS
    {
        public short IdUser { get; set; }
        public string System { get; set; }
        public short PhoneLine { get; set; }
        public System.DateTime LoginTime { get; set; }
        public string IP { get; set; }
    }
}
