//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherTrans
    {
        public int VTransID { get; set; }
        public int VoucherID { get; set; }
        public System.DateTime TransactDateTime { get; set; }
        public int LocationID { get; set; }
        public byte TransactType { get; set; }
        public string CurrCode { get; set; }
        public decimal CurrAmount { get; set; }
        public Nullable<int> TicketNumber { get; set; }
        public Nullable<int> ActiveTillID { get; set; }
        public Nullable<int> NewVoucherID { get; set; }
        public System.DateTime OpDate { get; set; }
    }
}
