//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int VoucherID { get; set; }
        public string VoucherNum { get; set; }
        public byte VoucherType { get; set; }
        public int LocationID { get; set; }
        public int IssuedTerminalID { get; set; }
        public byte VoucherStatus { get; set; }
        public System.DateTime IssuedDateTime { get; set; }
        public Nullable<System.DateTime> RedeemedDateTime { get; set; }
        public string CurrCode { get; set; }
        public decimal CurrBalance { get; set; }
        public decimal CurrOriginalBalance { get; set; }
        public Nullable<decimal> CurrRedeemedBalance { get; set; }
        public System.DateTime IssuedOpDate { get; set; }
        public Nullable<System.DateTime> RedeemedOpDate { get; set; }
    }
}
