//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAGERTYPE
    {
        public int IdWagerType { get; set; }
        public short IdProfile { get; set; }
        public string Description { get; set; }
        public byte NumTeams { get; set; }
        public byte WagerType1 { get; set; }
        public short WagerTypeOrder { get; set; }
    }
}
