//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSessionDetail
    {
        public int IdSession { get; set; }
        public string IdSport { get; set; }
        public int IdGame { get; set; }
        public short Play { get; set; }
        public short Rebate { get; set; }
        public short Pitcher { get; set; }
        public string Line { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Risk { get; set; }
        public Nullable<decimal> Win { get; set; }
        public Nullable<double> Odds { get; set; }
        public Nullable<double> Points { get; set; }
        public Nullable<double> BuyPoints { get; set; }
        public Nullable<short> Fav { get; set; }
        public int IdCreation { get; set; }
    }
}
