//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGSRestServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSession
    {
        public int IdSession { get; set; }
        public int IdPlayer { get; set; }
        public int IdProfile { get; set; }
        public int IdCall { get; set; }
        public int IdLineType { get; set; }
        public string NHLLine { get; set; }
        public string MLBLine { get; set; }
        public string LineStyle { get; set; }
        public string Currency { get; set; }
        public string IP { get; set; }
        public string Player { get; set; }
        public string Password { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LastActivity { get; set; }
    }
}
