//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestController.DGSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DGSService.IDGSWCFService")]
    public interface IDGSWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetInfoService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetInfoServiceResponse")]
        string agentGetInfoService(string agent, short idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGSWCFService/agentGetInfoService", ReplyAction="http://tempuri.org/IDGSWCFService/agentGetInfoServiceResponse")]
        System.Threading.Tasks.Task<string> agentGetInfoServiceAsync(string agent, short idUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDGSWCFServiceChannel : TestController.DGSService.IDGSWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DGSWCFServiceClient : System.ServiceModel.ClientBase<TestController.DGSService.IDGSWCFService>, TestController.DGSService.IDGSWCFService {
        
        public DGSWCFServiceClient() {
        }
        
        public DGSWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DGSWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DGSWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DGSWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string agentGetInfoService(string agent, short idUser) {
            return base.Channel.agentGetInfoService(agent, idUser);
        }
        
        public System.Threading.Tasks.Task<string> agentGetInfoServiceAsync(string agent, short idUser) {
            return base.Channel.agentGetInfoServiceAsync(agent, idUser);
        }
    }
}
